### ISSUE TITLE
Autoscaling support

### ISSUE THREAD

**Issue by iagomelanias** [summerwind/actions-runner-controller#10]
It would be great if pods could be adjusted automatically based on the number of pending workflows. I'm not sure if that's possible using the the current version of the Github Actions API or we should use a metrics server and try to keep the number of idle runners below X, but there should be a way to implement this feature. 🙂

**Comment by alexandrst88** [comment]
I think, It could be postpone, due to GitHub Actions will release Organizational runners officially.

**Comment by iagomelanias** [comment]
Oh, didn't know about that! Let's wait then 🙂

**Comment by mumoshu** [comment]
This might be possible today by poling the [list repository workflow runs API](https://developer.github.com/v3/actions/workflow_runs/#list-repository-workflow-runs) for runs w/ `status: queued` where `created_at` is before some threshold.

If anyone is willing to give it a shot, I'm more than happy to review and test!

As @alexandrst88 has noted, this is likely to change once the organization runners gets added though. Perhaps they'll add an another API to let us know which workflow runs is tied to which runner(repository-specific vs organizational vs etc)?

**Comment by jay2610** [comment]
Any update on this since we got ORG runners added?

**Comment by mumoshu** [comment]
Nothing on my end. Would you be willing to contribute it? The API to be used should now be https://developer.github.com/v3/actions/workflow-runs/#list-workflow-runs 😃

**Comment by jay2610** [comment]
I would more than happy to contribute but I don't know Go 😞. I tried to explore API and going try run one more controller with runner-controller deployment in JavaScript or even bash maybe. 
This should be the logic from my initial search.
1. Set the env variable for minimum number of runners set on RunnerDeployment
2. Query the number of pending jobs every minute. 
3. Based on that scale up RunnerDeployment (that's what I use)
3. If there is no pending job and more runners are Ideal then minimum number, scale down RunnerDeployment to min number.
