### ISSUE TITLE
Reposiroty names

### ISSUE THREAD

**Issue by Q-efx** [summerwind/actions-runner-controller#109]
Hey, your pattern check on repository names don´t allow underscores.

For example:

my_repo.

Which github allows as names.

**Comment by igorbrigadir** [comment]
does it fail when writing it like this:

```
repository: user/repo_name
```

or like this

```
repository: "user/repo_name"
```

or both?

**Comment by mumoshu** [comment]
Is that really the case? At least it should work today https://github.com/summerwind/actions-runner-controller/blob/6b77a2a5a841393c1b18ee203a67af7a987b1d0b/api/v1alpha1/runner_types.go#L39

Closing as resolved, but please feel free to reopen or submit another issue if necessary.
