### ISSUE TITLE
Deployment does not always restart pod after completion of a job.

### ISSUE THREAD

**Issue by bagel-dawg** [summerwind/actions-runner-controller#112]
Occasionally I will have a deployment that ends up in this state below:

```
[bagel@fort-kickass  ]$ kubectl get pods
NAME                                                READY   STATUS    RESTARTS   AGE
controller-manager-c5c7cd46-qbgrp                   2/2     Running   0          27h
helm-github-actions-runner-deployment-bc99p-8n6jt   1/2     Running   0          17m
tiller-deploy-7b56f5db68-5brkz                      1/1     Running   0          5d1
```

The output of the runner pod says that the job has completed and exited code 0. It's at this point that I would expect the pod to be restarted, but obviously it does not. This results in a never-ender queued job.

I can delete this pod and another will be spawned up to pick up the queued jobs.

**Comment by mumoshu** [comment]
@bagel-dawg Thanks! Can we merge this into #77, which is a long-standing bug that we're trying to fix?

**Comment by bagel-dawg** [comment]
@mumoshu ah, of course - I've seen that issue and didnt recognize it as related before I decided to write this one up.

**Comment by ZacharyBenamram** [comment]
@mumoshu - does this require investigation? Or are we already clear on a root cause?

**Comment by mumoshu** [comment]
@ZacharyBenamram Yes. It would be great if you could add more info to #77 so that I can investigate further
