### ISSUE TITLE
actions-runner.controller.yaml cannot install on kubernetes 1.18

### ISSUE THREAD

**Issue by BrendanGalloway** [summerwind/actions-runner-controller#116]
Attempting to install the actions runner controller on

`Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:04:18Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}` fails with the error `Error from server (Invalid): error when creating "https://github.com/summerwind/actions-runner-controller/releases/latest/download/actions-runner-controller.yaml": CustomResourceDefinition.apiextensions.k8s.io "runnerdeployments.actions.summerwind.dev" is invalid: [spec.validation.openAPIV3Schema.properties[spec].properties[template].properties[spec].properties[initContainers].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property, spec.validation.openAPIV3Schema.properties[spec].properties[template].properties[spec].properties[sidecarContainers].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property, spec.validation.openAPIV3Schema.properties[spec].properties[template].properties[spec].properties[containers].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property]`

The root cause appears to be #https://github.com/kubernetes/kubernetes/issues/91395

Please add a default to the protocol property or make it required so that the controller can install in 1.18

**Comment by igorbrigadir** [comment]
This seems like the same issue as #113
