### ISSUE TITLE
The CustomResourceDefinition "runnerdeployments.actions.summerwind.dev" is invalid:

### ISSUE THREAD

**Issue by jeffrey-kinesso** [summerwind/actions-runner-controller#130]
Hi all,
This has been happening for me for a few weeks and I was hoping it was fixed in #123 but no such luck:
```
master $ kubectl apply -f https://github.com/summerwind/actions-runner-controller/releases/latest/download/actions-runner-controller.yaml
Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply
namespace/actions-runner-system configured
customresourcedefinition.apiextensions.k8s.io/horizontalrunnerautoscalers.actions.summerwind.dev created
The CustomResourceDefinition "runnerdeployments.actions.summerwind.dev" is invalid:
* spec.validation.openAPIV3Schema.properties[spec].properties[template].properties[spec].properties[sidecarContainers].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property
* spec.validation.openAPIV3Schema.properties[spec].properties[template].properties[spec].properties[containers].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property
* spec.validation.openAPIV3Schema.properties[spec].properties[template].properties[spec].properties[initContainers].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property
master $
```

I've tried some debugging (hacking the CRD, use different k8s hosting) but haven't been able to figure it out.  Anyone else run into this?

Thanks

**Comment by igorbrigadir** [comment]
The latest release, https://github.com/summerwind/actions-runner-controller/releases/tag/v0.9.3 currently does not have the fix in #123 yet. 

If you want to try it, install kustomize https://kubernetes-sigs.github.io/kustomize/installation/ and:

```
git clone https://github.com/summerwind/actions-runner-controller.git
kustomize build config/default > latest.yaml
kubectl apply -f latest.yaml
```

**Comment by jeffrey-kinesso** [comment]
@igorbrigadir  - thank you so much, it worked!

**Comment by Hi-Fi** [comment]
> The latest release, https://github.com/summerwind/actions-runner-controller/releases/tag/v0.9.3 currently does not have the fix in #123 yet.
> 
> If you want to try it, install kustomize https://kubernetes-sigs.github.io/kustomize/installation/ and:
> 
> ```
> git clone https://github.com/summerwind/actions-runner-controller.git
> kustomize build config/default > latest.yaml
> kubectl apply -f latest.yaml
> ```

It's enough to just run "make release" to create release manifest from master. No need to install anything (except `go` and `make`)

**Comment by jeffrey-kinesso** [comment]
>It's enough to just run make release to create release manifest from master. No need to install anything (except go and make)

Thank you very much @Hi-Fi - this is a great tip!

**Comment by igorbrigadir** [comment]
> It's enough to just run `make release` to create release manifest from master. No need to install anything (except `go` and `make`)

Oh, that's even easier, thank you!
