### ISSUE TITLE
[Question] Does latest release contain latest master?

### ISSUE THREAD

**Issue by RRoundTable** [summerwind/actions-runner-controller#131]
Thank you for your repository.

I want to use this repo, but it seems that latest release doesn't represent latest master branch. 
I can't apply controller at kubectl 1.1.8.

Do you have a plan or due date to update release?

**Comment by jeffrey-kinesso** [comment]
@RRoundTable - In case it helps I had a similar issue related to latest commits not in release.  The workaround in this issue worked:
https://github.com/summerwind/actions-runner-controller/issues/130#issuecomment-712376189

**Comment by Hi-Fi** [comment]
There's 2 parts:
1. Manifests. Those can be generated with `make release`
2. Controller image. It has to be build locally and replace the one in manifests with own one. No "real" latest controller images built to Docker hub. `make docker-build, retag, push and use that custom image.

**Comment by RRoundTable** [comment]
Thanks.
