### ISSUE TITLE
Support for Runner Groups

### ISSUE THREAD

**Issue by ap0phi5** [summerwind/actions-runner-controller#137]
Great operator, thanks. Perhaps I've just not figured out how to configure it, but is there a way to assign the `RunnerDeployment` to a Runner Group for an Org? I've not seen use of the API in a repo code-search;  `/orgs/{org}/actions/runner-groups`

https://docs.github.com/en/free-pro-team@latest/rest/reference/actions#self-hosted-runner-groups

**Comment by Hi-Fi** [comment]
At least when checking docs it states
> The self-hosted runner groups REST API is available with GitHub Enterprise Cloud

So it would be quite hard to develop without that. Also it seems that the runner has to be there before it can be added to group, so API still needs admin access to org (which is quite "overkill" to distribute tokens with that high permissions just to register runners).

**Comment by Hi-Fi** [comment]
Also runners can't be added directly to group, but they need to be moved there according https://docs.github.com/en/enterprise-server@2.22/actions/hosting-your-own-runners/managing-access-to-self-hosted-runners-using-groups#moving-a-self-hosted-runner-to-a-group.

Also that API (https://docs.github.com/en/free-pro-team@latest/rest/reference/actions#add-a-self-hosted-runner-to-a-group-for-an-organization) is not available at the public Github. 

If original need was for Enterprise, this can be developed. I think creation of runner group and assigning rights to it should still be user's responsibility, and only that adding runner to group should be used.

**Comment by ap0phi5** [comment]
Yep, this will be difficult if you don't have access to GitHub Enterprise (Cloud). If I get a chance I'll have a go at it myself later.
 
For brevity, just going to show what runner groups at **org-scope** looks like from the UI. Runners currently land in the `default` group:
![image](https://user-images.githubusercontent.com/5719506/97983694-9af23d80-1dcd-11eb-8a81-4094c196fe94.png)

And this is what runner groups at **enterprise-scope** from the UI looks like:
![image](https://user-images.githubusercontent.com/5719506/97983900-e3116000-1dcd-11eb-80aa-8b7133a8d81b.png)

Theres no option to add/move runners to groups from the UI currently, so we will have to figure how to do this from an API call.

**Comment by jbuettnerbild** [comment]
how i see this, only a "--runnergroup" parameter has to add here: https://github.com/summerwind/actions-runner-controller/blob/6d78fb07b3cf8f0f8ab85282539d7d7bcecea0e2/runner/entrypoint.sh#L29

i tested it in our public org (not github enterprise) with success

**Comment by Hi-Fi** [comment]
@jbuettnerbild Interesting, as GH own documentation stated that runners can be only added to default group and then moved. But if that works, it's very easy to add.

**Comment by jbuettnerbild** [comment]
i have copied your entrypoint.sh and add the parameter like this:
`./config.sh --unattended --replace --name "${RUNNER_NAME}" --url "https://github.com/${ATTACH}" --token "${RUNNER_TOKEN}" ${LABEL_ARG} --runnergroup lean`
Than i have build our own image of the summerwind/actions-runner-dind:v2.273.5 because we need maven.
And i the result is clear. i didn't need to manual move the runner from default to our runner group:
![Bildschirmfoto 2020-11-04 um 11 25 50](https://user-images.githubusercontent.com/34340440/98099990-8a56cb80-1e90-11eb-805f-de44dc369fdf.png)

**Comment by Hi-Fi** [comment]
Nice. I think group was there already, and the argument doesn't create group if it doesn't exist?

**Comment by Hi-Fi** [comment]
@jbuettnerbild Can you make PR of that?

**Comment by jbuettnerbild** [comment]
Im not sure if i will find all places to add this but i can try. give me a day.

**Comment by jbuettnerbild** [comment]
sorry unfortunately haven't gotten to it yet.
