### ISSUE TITLE
Support multiple secrets (and Github URLs)

### ISSUE THREAD

**Issue by Hi-Fi** [summerwind/actions-runner-controller#148]
Currently there's only one secret that's used by the `contoller-manager`. Also because of the way how `actions-runner-controller` works, separate secrets or public and enterprise github separation needs to be made at the separate clusters.

I don't have directly idea how to do this, but it would be nice to...
- Support multiple secret (maybe even secrets from namespaces, so there can be per-namespace created runners that use secret from their own namespace)
- Support multiple Github installations (maybe bound secret with URL?)

**Comment by Natanande** [comment]
Would it be possible to modify the ClusterRoles into namespaced Roles and deploy multiple instances of the Operator, or would this break some functionality?

**Comment by mumoshu** [comment]
> Would it be possible to modify the ClusterRoles into namespaced Roles and deploy multiple instances of the Operator, or would this break some functionality?

This should work

**Comment by mumoshu** [comment]
> ClusterRoles into namespaced Roles

I think the use of the ClusterRole is actually fine. We should use RoleBinding rather than ClusterRoleBinding, so that we can provide fine-grained access to namespaces in which RoleBindings are.

**Comment by mumoshu** [comment]
This should be a good fit for our helm chart. Maybe we could define values like the below to restrict the namespaces to be managed:

```
managedNamespaces:
- foo
- bar
```

This would create two RoleBindings in the namespaces `foo` and `bar`, where each RoleBinding provides the controller's serviceaccount access to runnerdeployments, runnerreplicasets, runners, and horizontalrunnerautoscalers in `foo` or `bar`, by binding the ClusterRole to the controller's serviceaccount.

**Comment by Natanande** [comment]
That would be perfect for for our use case!

**Comment by tzejohn** [comment]
Is there any updated guidance on supporting both cloud hosted and on-prem enterprise instances with runners running in a single EKS cluster? Or is this not possible, and I would need another EKS cluster?

**Comment by mumoshu** [comment]
You can freely deploy two or more actions-runner-controller in different controller namespaces and watch namespaces today. Just use one controller for e.g. GitHub cloud and another for your GitHub Enterprise, etc.

Closing as resolved!
