### ISSUE TITLE
Runners being terminated after each workflow

### ISSUE THREAD

**Issue by cartucciam** [summerwind/actions-runner-controller#156]
I am seeing the pods being terminated after each job they run, is this the expected behaviour?

**Comment by jeffj254** [comment]
Seems like it's probably to make pods ephemeral (as all containers should be) and eliminate the possibility of data rot corrupting future jobs.

That said, I have noticed that this behavior is aggressive enough that if the runner fails to transfer the job logs back to GitHub on the first shot, the pod will be terminated and the logs lost.

**Comment by mumoshu** [comment]
@cartucciam As @jeffj254's kindly noted, that's expected behaviour today.

I wished #103 could defer the termination until the logs are fully transferred, but apparently, it isn't. That being said, I'm considering to add an option to toggle the runner to be ephemeral or not. Maybe `ephemeral: false` to disable the current behaviour?

**Comment by Hi-Fi** [comment]
I think it's good that pods are removed (and recreated) after the run to prevent the possibility to mix data (or installed things) between runs. As pipeline can also install OS packages and interpreters, it would be quite annoying to see time-to-time failures when versions are changing between runs.

**Comment by cartucciam** [comment]
> I think it's good that pods are removed (and recreated) after the run to prevent the possibility to mix data (or installed things) between runs. As pipeline can also install OS packages and interpreters, it would be quite annoying to see time-to-time failures when versions are changing between runs.

I agree. I have asked only to be sure it wasn't an issue with my configuration. Thanks for the replies
