### ISSUE TITLE
labels no longer working

### ISSUE THREAD

**Issue by reiniertimmer** [summerwind/actions-runner-controller#161]
It seems that since one of the updates the labels are no longer working.

Could it be that this is broken from the GitHub runner itself? The message I see is:

```
Unrecognized command-line input arguments: 'labels k8s-runner'. For usage refer to: .\config.cmd --help or ./config.sh --help
```

**Comment by reiniertimmer** [comment]
The `--label` commandline argument still seems to be working on the runner itself, so it could be that something's broken in the shell script itself. I'll attempt to make some sense of this and see if I can find out what's the issue

**Comment by reiniertimmer** [comment]
Found it.

Commit dcf8524b5c200879c723edb11ca62b8e3cd837ac (PR #157) adds quotes around the `${LABEL_ARG}`, effectively passing the label argument as a single argument `--labels x,y,z`. These should be 2 arguments of course, so removing the labels will solve this issue

I will issue a PR for this

**Comment by ap0phi5** [comment]
I'm seeing this also for the `runnergroup` argument - I'm assuming this must be the same issue.
```Github endpoint URL https://github.com/
Unrecognized command-line input arguments: 'runnergroup runner-group-01'. For usage refer to: .\config.cmd --help or ./config.sh --help```

**Comment by ZacharyBenamram** [comment]
doesnt look as if the new addition in https://github.com/summerwind/actions-runner-controller/pull/157 resolves the label issue. Labels are still not being applied to the runners
