### ISSUE TITLE
how to mount additional volumes with runners

### ISSUE THREAD

**Issue by acesir** [summerwind/actions-runner-controller#163]
do runners support mounting additional volumes (PVC's and host volumes). I tried looking for additional documentation on this but found none. Trying a few things it does not seem to work. Any guidance that can be provided is helpful.

**Comment by tabossert** [comment]
@acesir you closed this, was there an answer?

**Comment by tabossert** [comment]
ahh I found it in CRD

**Comment by tabossert** [comment]
I see how to attach an existing volume, but not a way to create a pvc at pod creation time
