### ISSUE TITLE
GitHub API Auth Failing on 0.11.2?

### ISSUE THREAD

**Issue by callum-tait-pbx** [summerwind/actions-runner-controller#181]
Yo,

I've torn everything down and tried to deploy again with a PAT instead of a app incase github apps are broken in 0.11.2 and got an error, as I've had issues authing with both as a github app and using a PAT token I am starting to think auth is broken in 11.2 and it's not just my environment? I deployed a new namespace today to deploy this into to ensure there was no crap sitting around causing issues. https://github.com/summerwind/actions-runner-controller/pull/167 recently fixed some issues with token registration, are we sure GitHub App registeration and / or PAT auth with the API works as described by the README.md?

**Env ** 0.11.2
**Token Scopes** Repo (all sub scopes), admin:org (all sub scopes)
The user is an org admin and created the repos I have included in my runner yaml. 

**Error Thrown**
_Note I've removed the actual token from the error and replaced it with $REPLACED_TOKEN_VALUE_
```json
2020-11-12T22:17:30.693Z	ERROR	controller-runtime.controller	Reconciler error	{"controller": "runner", "request": "sre-actions-runner-system/sre-actions-runners-runner-deployment-dk7q8-dk5c9", "error": "failed to create registration token: Post \"https://api.github.com/orgs/photobox/actions/runners/registration-token\": net/http: invalid header field value \"Bearer $REPLACED_TOKEN_VALUE\\n\" for key Authorization"}
github.com/go-logr/zapr.(*zapLogger).Error
	/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:258
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:232
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:211
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190913080033-27d36303b655/pkg/util/wait/wait.go:152
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190913080033-27d36303b655/pkg/util/wait/wait.go:153
k8s.io/apimachinery/pkg/util/wait.Until
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190913080033-27d36303b655/pkg/util/wait/wait.go:88
```

**Steps to reproduce**
1. Deploy PAT token configured as described
2. Build the manifest `kustomize build ./default > ./manifest.yaml`
3. Deploy manifest `kubectl apply -f ./manifest.yaml`
4. Deploy runners `kubectl apply -f ./runners.yaml`
5. Check manager logs `kubectl logs controller-manager-777fb76ddb-7zwzk -c manager`

**Comment by callum-tait-pbx** [comment]
Fixed

**Cause** `echo $TOKEN | base64` adds a new line at the end of the output causing the error
*Solution* `echo -n $TOKEN | base64` ensures no new line is added and the token should work

**Comment by mumoshu** [comment]
@callum-tait-pbx Thanks! Perhaps we'd better enhance our docs for this? As I've written in https://github.com/summerwind/actions-runner-controller/issues/171#issuecomment-725244272 I have experienced it myself before.
