### ISSUE TITLE
Publish helm chart to a registry

### ISSUE THREAD

**Issue by ahmad-hamade** [summerwind/actions-runner-controller#195]
Is there any plan to publish the helm chart to some sort of registry?

Maybe to [artifacthub](https://artifacthub.io/)?

**Comment by mumoshu** [comment]
I'm looking for a solution that makes the process super easy. It would be best if it's matter of just passing `helm packate` result into another single command.

**Comment by callum-tait-pbx** [comment]
It would be really great if we could perhaps make use of Helms chart releaser to package and release the chart onto github pages. This would be simple and self managing. I'll put together a PR? Once it's in pages people (like myself :D) can hook onto the releases allowing them to be sync with internal feeds.

https://github.com/marketplace/actions/helm-chart-releaser

**Comment by pierluigilenoci** [comment]
@mumoshu any update?

**Comment by ahmad-hamade** [comment]
There were 2 releases published so far for helm chart but I can't find a way to add helm repo as I'm getting the following error:

```
helm repo add runner https://github.com/summerwind/actions-runner-controller
Error: looks like "https://github.com/summerwind/actions-runner-controller" is not a valid chart repository or cannot be reached: failed to fetch https://github.com/summerwind/actions-runner-controller/index.yaml : 404 Not Found
```

@mumoshu Do you have any update on this?

**Comment by donovanmuller** [comment]
@ahmad-hamade use:

```console
$ helm repo add runner https://summerwind.github.io/actions-runner-controller/
"runner" has been added to your repositories

$ helm search repo actions-runner-controller
NAME                            	CHART VERSION	APP VERSION	DESCRIPTION
runner/actions-runner-controller	0.2.0        	0.16.0     	A Kubernetes controller that operates self-host...
```

**Comment by ahmad-hamade** [comment]
Thank you @donovanmuller. I was using the wrong repo URL.

I will be closing this issue now.
