### ISSUE TITLE
Release v0.13.0 lacks manifest yaml artifact

### ISSUE THREAD

**Issue by Warashi** [summerwind/actions-runner-controller#208]
Release v0.13.0 lacks `actions-runner-controller.yaml`, so I cannot apply.
Please add.
https://github.com/summerwind/actions-runner-controller/releases/tag/v0.13.0

**Comment by Warashi** [comment]
The cause seems to be fail in this job https://github.com/summerwind/actions-runner-controller/actions/runs/382154327

**Comment by mumoshu** [comment]
Thanks for reporting!
Seems like this is due to the deprecation of `set-env`. I'd need to change that to whatever alternative
