### ISSUE TITLE
Docker caching

### ISSUE THREAD

**Issue by vitobotta** [summerwind/actions-runner-controller#22]
Hi! I just installed this and am happy I can delete the dedicated VPS for my runner. I am adapting my workflows, but I am having problems with Docker builds, because it's not caching image layers. I exec'ed into the runner and saw that after each build `docker images` returns nothing. 

What can I do to prevent each build from starting from scratch?

Thanks!

**Comment by vitobotta** [comment]
Also, it seems I cannot run commands with sudo?

**Comment by mumoshu** [comment]
> Also, it seems I cannot run commands with sudo?

Probably we need to add the `runner` user to sudoers?

https://github.com/summerwind/actions-runner-controller/blob/b8b4ef4b60a45fe647a19a6f56130eb3449a9a99/runner/Dockerfile#L25

Would you mind giving it a shot? I'm more than happy yo review if you could submit a PR for that!

**Comment by mumoshu** [comment]
> it's not caching image layers

This is by-design atm. The `--once` flag we're consistently passing in the runner entrypoint [here](https://github.com/summerwind/actions-runner-controller/blob/f2d3ca672f5a5a2c9deba852eab2286a5a3984e6/runner/entrypoint.sh#L22) instructs the runner to stop/restart from the scratch on each build.

Perhaps we can have an additional field in the Runner CRD to make it configurable.

Also - `--once` is preferable for reproducible builds. So an alternative way would be to deploy an in-cluster docker image registry for caching images, from where you can pull the image on each build.

Which way do you prefer?

**Comment by vitobotta** [comment]
Hi, I can send a small PR for the user thing.

As for the caching, do you mean `--cache-from`?

**Comment by mumoshu** [comment]
Yeah - More concretely, I believe adding your docker-build a `--cache-from` to a in-cluster docker registry, and adding `docker push` against the in-cluster registry in the very end of your build would help reducing the build time.

**Comment by vitobotta** [comment]
OK, I will try installing Harbor in my cluster and use that. Thanks for the suggestion!

**Comment by vitobotta** [comment]
I've been using Harbor as in cluster registry and --cache-from. It's not as fast as using the local cache due to the pull required, but it's a lot better than building from scratch. Thanks a lot again, this project saved me the time to do something similar :)
