### ISSUE TITLE
Runner upgrade to 2.276.0 failed

### ISSUE THREAD

**Issue by jolestar** [summerwind/actions-runner-controller#264]
Runner auto-upgrade to 2.276.0  failed 

```text
2021-01-20 01:59:58Z: Listening for Jobs
Runner update in progress, do not shutdown runner.
Downloading 2.276.0 runner
Waiting for current job finish running.
Generate and execute update script.
Runner will exit shortly for update, should back online within 10 seconds.
renamed '/runner/_diag/SelfUpdate-20210120-020013.log' -> '/runner/_diag/SelfUpdate-20210120-020013.log.failed'
Runner listener exited with error code 4
Runner listener exit with undefined return code, re-launch runner in 5 seconds.
Starting Runner listener with startup type: service
Started listener process
events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: spawn /runner/bin/Runner.Listener ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn /runner/bin/Runner.Listener',
  path: '/runner/bin/Runner.Listener',
  spawnargs: [ 'run', '--startuptype', 'service', '--once' ]
}
```

**Comment by mumoshu** [comment]
@jolestar Hey! I was thinking that this might be due to #252 that can be fixed via #253. I thought I'd release it soon but had no time to test it. Could you confirm/test it if possible?

**Comment by jolestar** [comment]
> @jolestar Hey! I was thinking that this might be due to #252 that can be fixed via #253. I thought I'd release it soon but had no time to test it. Could you confirm/test it if possible?

Ok, I try to build a new image. the latest base image is still v2.275.1 ?

**Comment by jolestar** [comment]
@mumoshu  I read  #253, If I want to test it, do I just need to build a new runner image?

**Comment by mumoshu** [comment]
@jolestar You need both runner and controller images upgraded, as the new controller code depends on the new runner image

**Comment by shadiramadan** [comment]
@jolestar were you able to resolve the self update issue?

**Comment by jolestar** [comment]
@shadiramadan  resolve by #253

**Comment by terry-yolabs** [comment]
I am hitting the same error.  I wasn't able to resolve it by creating containers using the branch in #253.  This error is blocking development work on a new CD workflow so I'm hoping to find a solution quickly.  Is there something I can do to assist testing?

**Comment by shadiramadan** [comment]
@mumoshu Do you have an ETA on when you can incorporate these fixes into #253 for a release?  Just want to know if I need to follow @achedeuzot recommendations and make a local build or wait.

**Comment by kaykhancheckpoint** [comment]
Also experiencing this now

**Comment by kaykhancheckpoint** [comment]
@achedeuzot do you have your docker image available publically somewhere?

**Comment by hfuss** [comment]
Hi folks, we just tested @achedeuzot's fixes on https://github.com/hfuss/actions-runner-controller/tree/testing-self-update-fix-2.276.0 and also had success. You find the images here in the interim:

* [`brix4dayz/actions-runner:v2.275.1`](https://hub.docker.com/layers/brix4dayz/actions-runner/v2.275.1/images/sha256-45e6b4871d11fa595b924f71191074106284fef5d79542dd9cb67faf1463eaaf?context=explore)
* [`brix4dayz/actions-runner-controller:v0.16.1-prerelease`](https://hub.docker.com/layers/brix4dayz/actions-runner-controller/v0.16.1-prerelease/images/sha256-546c748efbc076037c881b7395225521fca96b0e1d9a00522c7fcf5b551b8825?context=explore)

**Comment by kaykhancheckpoint** [comment]
@hfuss great

The actions-runner-controller image needs to be replaced with the image found in  `https://github.com/summerwind/actions-runner-controller/releases/latest/download/actions-runner-controller.yaml` is that right?

**Comment by hfuss** [comment]
@kaykhancheckpoint correct!

**Comment by jonico** [comment]
2.276.0 is not compatible with GitHub Enterprise Server - see https://github.com/actions/runner/pull/896#issuecomment-764016208

I would recommend upgrading to the latest version: https://github.com/actions/runner/pull/931

**Comment by int128** [comment]
I've updated actions-runner-controller to v0.16.1 and it works well. I manually deleted the old runners and the controller automatically created new runners. Thank you for the great work.

**Comment by e36-cicd** [comment]
Just a quick note on this - we noticed that the deployment for the controller has an image pull policy of "IfNotPresent", which doesn't update the image if it already exists. This has caused issues for us after merging this fix, and we had to make it pull again for this fix to work (since the old controller still created an emptyDir of '/runner/externals', crashing the update).
