### ISSUE TITLE
unable to mv /runnertmp to /runner

### ISSUE THREAD

**Issue by alex-mozejko** [summerwind/actions-runner-controller#283]
hi, 

it looks like the entrypoint.sh is trying to `mv /runnertmp/* /runner` as the 'runner' user. 

however `/runnertmp/patched` is owned by 'root' so 'runner' can't remove (mv). 

maybe the dockerfile can `COPY --chown=runner:docker patched $RUNNER_ASSETS_DIR/patched`  or the entrypoint can `sudo mv` or `cp -r`

**Comment by mumoshu** [comment]
This one should have been fixed via #284 thanks to you! Closing as resolved, but please feel free to reopen if necessary.
