### ISSUE TITLE
Tag Mutability issues

### ISSUE THREAD

**Issue by ap0phi5** [summerwind/actions-runner-controller#285]
Because our internal container registry uses immutable tags (ie, write a tag once, then it can no longer be changed), we seem to be getting into a position where we can't consume updates: (we are also stuck with this version of v2.275.1 where we are seeing this issue: https://github.com/summerwind/actions-runner-controller/issues/255)

Internal Registry:
```
actions-runner:v2.275.1
  digest: sha256:38c92b3c2783908c2a34a1467342746c9598fae67a212e99d038b5aa309c5a9c
```
Pulled from Docker Hub:
```
docker images --digests
REPOSITORY                      TAG                 DIGEST                                                                    IMAGE ID            CREATED             SIZE
summerwind/actions-runner       v2.275.1            sha256:22460b3bf52cd3260f3d1f9fcf5bcad610d308ab59d2a5c13434fcaefd023f5e   f192bd97d58f        8 days ago          704MB
```

I'll propose a PR that removes the hardcoded versioning and references the `GITHUB_RUN_NUMBER` so that tags are generated dynamically. https://docs.github.com/en/actions/reference/environment-variables#default-environment-variables

**Comment by jeroen-s** [comment]
Running into this issue as well. Would like to see all tags except "latest" to be immutable in the docker hub repos.

**Comment by jeroen-s** [comment]
Another related issue: I noticed in the "summerwind/actions-runner-controller" repo that the "latest" tag is being updated without a new version tag being added. I would like to see new version tags for all new docker images being added.

**Comment by mumoshu** [comment]
@jeroen-s I believe `$RUNNER_VERSION-$COMMIT_SHA` added via #286 is what you're looking for. Could you confirm?
