### ISSUE TITLE
Add support for enterprise runners

### ISSUE THREAD

**Issue by zetaab** [summerwind/actions-runner-controller#289]
readme currently says `Enterprise level runners are not working yet as there's no API definition for those.`

However, that is not true anymore. APIs are published and can be seen in https://docs.github.com/en/rest/reference/enterprise-admin#create-a-registration-token-for-an-enterprise for instance

**Comment by callum-tait-pbx** [comment]
I think the biggest issue with developing this is testing, if someone who has an enterprise account can offer their time and env to test I'm sure it could be done @mumoshu

**Comment by zetaab** [comment]
@callum-tait-pbx I have environment which has GHE with these features. It seems that I need first start implementing stuff to google/go-github repo, its missing functions

**Comment by zetaab** [comment]
https://github.com/google/go-github/pull/1789
