### ISSUE TITLE
How to make the build more stable with self-hosted runner

### ISSUE THREAD

**Issue by chenrui333** [summerwind/actions-runner-controller#30]
I deployed a fleet of self-hosted runners yesterday for my team, it looks like it does the work, but the process seems little bit flaky.

Two issues I have seen multiple times:
```
##[error].github/workflows/api.yml (Line: 107, Col: 16):
##[error]The template is not valid. .github/workflows/api.yml (Line: 107, Col: 16): The operation was canceled.
```

Or something like this:
![image](https://user-images.githubusercontent.com/1580956/79010136-52242000-7b2f-11ea-8f5e-cedda3f42461.png)

The rerun just turned the build green.

So I am curious if there is anyway that I can retry or how to make the build process more stable. Thanks!

**Comment by summerwind** [comment]
Thank you for using this!
I don't think this is a Runner issue, is the "Line: 107, Col: 16" in the Workflow file written properly?

**Comment by chenrui333** [comment]
yes, restarting the build just turned green again.

**Comment by chenrui333** [comment]
Running into this issue again, I wonder if there is better way of addressing this issue (instead of re-running the job).

**Comment by mumoshu** [comment]
@chenrui333 Just curious but what's in line 107 of your .github/workflows/api.yml? I think the error message is just saying that one of github actions functions that is called there is timing out.

**Comment by chenrui333** [comment]
what I am thinking is whether we have some sort of retry when there is failure like that?

**Comment by mumoshu** [comment]
@chenrui333 I beileve no. We have no known way to configure per-step retries from the actions-runner-controller side.

If you need that, I think all we can do would be submitting a feature request(or a support/bug ticket?) to the upstream forum(https://github.community/t5/GitHub-Actions/bd-p/actions)

**Comment by chenrui333** [comment]
That sounds about right, I will reach out to the community about ideas.

**Comment by chenrui333** [comment]
Looks like there is a community thread about this. 
https://github.community/t5/GitHub-Actions/Ability-to-rerun-just-a-single-job-in-a-workflow/m-p/41629

Closing this issue now.
