### ISSUE TITLE
Use `latest` docker image tags for new releases only

### ISSUE THREAD

**Issue by mumoshu** [summerwind/actions-runner-controller#302]
#300 made me realize that some people use `latest` tag for the controller image in production deployments. I believe changing our workflow to update `latest` tag only on new releases makes things a bit more reliable for them.

Currently `latest` is automatically updated on each new commit in the main branch. As I usually do some additional manual tests before releasing a new version of the controller, updating `latest` only on new releases result in the controller deployments get updated only with manually tested releases.

From a maintainer's perspective, reports like #300 is SUPER HELPFUL as I can notice/confirm that there's indeed issue(s) that I missed while reviewing or limited manual tests I often do before merging PRs.

So, I'd like to introduce another tag, `canary` for one that is updated on every commit.

**Comment by donovanmuller** [comment]
@mumoshu related to this, is there a reason that the Helm chart uses [`tag: "latest"`](https://github.com/summerwind/actions-runner-controller/blob/addcbfa7ee22848d6df96c626596dcc82536812c/charts/actions-runner-controller/values.yaml#L25) and not blank to pick up the `appVersion` which would be much more stable?

**Comment by mumoshu** [comment]
@donovanmuller Ah, good catch! Probably we'd better just use `appVersion` and make the default `tag` empty. I had written `tag: "latest"` without thinking much.

**Comment by callum-tait-pbx** [comment]
See my comments on my PR for more details but would it not be better to set the default in the `values.yaml` that is bundle with the chart, the Helm chart `AppVersion` really doesn't mean anything for this project.
