### ISSUE TITLE
Error when launching a container on the self-hosted runner

### ISSUE THREAD

**Issue by tzejohn** [summerwind/actions-runner-controller#304]
I am just getting this setup in our EKS cluster. In my specific case, I need to run some `aws` commands in one of my steps, and so I thought I would do that by running a container with the aws-cli in it for those steps. Something like:

```
setup_k8s_namespace:
    runs-on: self-hosted
    container:
      image: amazon/aws-cli:latest
```

When the container is being launched, I am getting the following error.

```
...
  9b684ebecc59: Pull complete
  ebabd9bcc7c3: Pull complete
  Digest: sha256:5bf6e221a787b20d5a2bcedb0ac5cac7ab191defb786003ad326ab075b0218c7
  Status: Downloaded newer image for amazon/aws-cli:latest
  docker.io/amazon/aws-cli:latest
  /usr/local/bin/docker create --name 3b35933a78fa4d6ab419fd49af98e2f9_amazonawsclilatest_23a138 --label 60e226 --workdir /__w/unity/unity --network github_network_a44834cc6a3549e381f62a1fea51a9ed  -e "HOME=/github/home" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/runner/_work":"/__w" -v "/runner/externals":"/__e":ro -v "/runner/_work/_temp":"/__w/_temp" -v "/runner/_work/_actions":"/__w/_actions" -v "/runner/_work/_tool":"/__w/_tool" -v "/runner/_work/_temp/_github_home":"/github/home" -v "/runner/_work/_temp/_github_workflow":"/github/workflow" --entrypoint "tail" amazon/aws-cli:latest "-f" "/dev/null"
  5b22da304c2a208299d59aa98f43634eca4d1eea282335b30307d839608d48c7
  /usr/local/bin/docker start 5b22da304c2a208299d59aa98f43634eca4d1eea282335b30307d839608d48c7
Error response from daemon: io.containerd.runc.v2: failed to adjust OOM score for shim: set shim OOM score: write /proc/284/oom_score_adj: invalid argument
```

I have seen another posting where this happens in DinD with docker version 20, but I think we are running 19 here.

https://discourse.drone.io/t/docker-build-failures-from-oom-score-adjustments/8492

Is there anything I should try?

**Comment by erikkn** [comment]
Try setting your Pod resource requests & limits

**Comment by mumoshu** [comment]
// Got to think if we'd need to bump the default resource requests/limits, if setting requests/limits fixes this kind of problem. I've seen another issues that were due to runner resource shortage. And they're currently significantly lower than the resources available to GitHub-managed runners, which may result in jobs fine on managed runners fail on self-hosted runners.

**Comment by callum-tait-pbx** [comment]
I think aligning the resource requests/limits with github managed runners makes a lot of sense as I would expect similar default behaviour between self-hosted and github managed runners

**Comment by tzejohn** [comment]
Thanks. Increasing the resources addressed the issue.
