### ISSUE TITLE
 Failed to get new registration token 

### ISSUE THREAD

**Issue by sandeepraj-chandrakant-bhandari-db** [summerwind/actions-runner-controller#329]
Hi ,

I am getting error while deploying the new runner. 

the action controller gives the below error :

```2021-02-18T05:46:03.476Z    DEBUG    controller-runtime.manager.events    Warning    {"object": {"kind":"Runner","namespace":"default","name":"example-runn │
│ 2021-02-18T05:46:03.475Z    ERROR    controller-runtime.controller    Reconciler error    {"controller": "runner", "request": "default/example-runner", "er │
│ github.com/go-logr/zapr.(*zapLogger).Error       

2021-02-18T05:46:19.028Z    DEBUG    controller-runtime.manager.events    Warning    {"object": {"kind":"Runner","namespace":"default","name":"example-runn │
│ 2021-02-18T05:46:39.594Z    ERROR    controllers.Runner    Failed to get new registration token    {"runner": "example-runner", "error": "failed to create  │
│ github.com/go-logr/zapr.(*zapLogger).Error 
````
I am simply trying to register a runner to a repository.

**Comment by mumoshu** [comment]
@sandeepraj-chandrakant-bhandari-db Hey! This can happen in many ways - the lack of permissions on the github app or personal access token, if it's token and you're using organisational runners the token needs to be created by a github account that has admin priv to the org, etc.

Can you give me brief overview of your setup?

**Comment by sandeepraj-chandrakant-bhandari-db** [comment]
@mumoshu hey.. thank you for the response. I found the issue was because I was passing api url  in enterprise URL while setting the environment. 

It is now fixed and runners were registered.
