### ISSUE TITLE
[Bug] Group incorrectly set for docker-in-docker runner image

### ISSUE THREAD

**Issue by audip** [summerwind/actions-runner-controller#336]
## Overview
[Docker-in-docker runner Dockerfile](https://github.com/summerwind/actions-runner-controller/blob/master/runner/dindrunner.Dockerfile) sets the group for `/opt/hostedtoolcache` to be `runner` instead of `docker`. In the context of that dockerfile, `runner` is the user who is part of the `docker` group

## Problem

```
The default tool cache directory (/opt/hostedtoolcache on Linux, /Users/runner/hostedtoolcache on macOS, C:/hostedtoolcache/windows on Windows) must be writable by the runner user. This is necessary since the Ruby builds embed the install path when built and cannot be moved around.
/home/runner must be writable by the runner user.
```

## Solution

Set group correctly to `docker` in both [runner dockerfile](https://github.com/summerwind/actions-runner-controller/blob/master/runner/Dockerfile) and [dindrunner dockerfile](https://github.com/summerwind/actions-runner-controller/blob/master/runner/dindrunner.Dockerfile)

**Comment by mumoshu** [comment]
@audip Thanks for reporting! I can confirm that you're definitely correct:

From a locally run runner container I can see the below that indicates that the situation is exactly as what you described.

```
$ grep runner /etc/group
sudo:x:27:runner
runner:x:1000:
docker:x:1001:runner
```

**Comment by inventionlabsSydney** [comment]
This change seems to now block actions from writing to that directory:
Container creates in the docker sidecar:
``` 
/usr/local/bin/docker create --name 35a222792c704687b11a1fd9b7386df4_python38_be1c94 --label 60e226 --workdir /__w/<redacted>/<redacted> --network github_network_8010b395b333474cbfbd584f14ee5d21 --user 1000 -e "HOME=/github/home" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/runner/_work":"/__w" -v "/runner/externals":"/__e":ro -v "/runner/_work/_temp":"/__w/_temp" -v "/runner/_work/_actions":"/__w/_actions" -v "/opt/hostedtoolcache":"/__t" -v "/runner/_work/_temp/_github_home":"/github/home" -v "/runner/_work/_temp/_github_workflow":"/github/workflow" --entrypoint "tail" python:3.8 "-f" "/dev/null"
```

Then when the action is running:

```
Run github/codeql-action/init@v1
  with:
    languages: python
    token: ***
    matrix: {
    "language": "python"
  }
    setup-python-dependencies: true
    debug: false
/usr/local/bin/docker exec  4b22ef4e46484e2a92a40b99bbf6d0fafa80ec04defa439d38b11[17](<redacted>#step:5:17)e3[5](<redacted>#step:5:5)1d435[6](<redacted>step:5:6) sh -c "cat /etc/*release | grep ^ID"
Setup CodeQL tools
  Looked for CodeQL bundle in github/codeql-action on <redacted> but got error HttpError: Not Found.
  Downloading CodeQL tools from https://github.com/github/codeql-action/releases/download/codeql-bundle-20220120/codeql-bundle-linux64.tar.gz. This may take a while.
  /bin/tar xz --warning=no-unknown-keyword --overwrite -C /__w/_temp/ec69d4fc-[7](<redacted>#step:5:7)931-473d-ac54-3744c6b70557 -f /__w/_temp/3951b2bf-5a7d-496b-9cc[8](<redacted>#step:5:8)-cca76[9](<redacted>#step:5:9)f0f91e
  Error: Error: EACCES: permission denied, mkdir '/__t/CodeQL'
  Error: Unable to download and extract CodeQL CLI
  Error: Unable to download and extract CodeQL CLI
      at setupCodeQL (/__w/_actions/github/codeql-action/v1/lib/codeql.js:269:[15](<redacted>#step:5:15))
 ```

This is because the container running the action is running as a unprivileged used:
```
I have no name!@bc008fe83b1d:/__w/<redacted>/redacted>$ ls -lah /
total 88K
drwxr-xr-x   1 root root 4.0K Mar 22 00:02 .
drwxr-xr-x   1 root root 4.0K Mar 22 00:02 ..
-rwxr-xr-x   1 root root    0 Mar 22 00:02 .dockerenv
drwxr-xr-x   6 1000 1000 4.0K Mar 22 00:01 __e
drwxr-xr-x   2 root root 4.0K Mar 22 00:02 __t <-- This is the folder in question.
drwxrwxrwx   6 1000 1001 4.0K Mar 22 00:01 __w
```

As such, I believe this change has now broken other implementations, can we not customise this?

**Comment by mumoshu** [comment]
@inventionlabsSydney Thanks for reporting!

Just wondering, but who creates the directory `__t` in this case?

**Comment by Gentoli** [comment]
Have the a similar issue when the container is not running as root.

``` log
/usr/local/bin/docker exec  b5cccc6b4bb3e707f72cc4[16](https://github.com/Gentoli/okd-machine-os/runs/6563450243?check_suite_focus=true#step:5:17)a0bb530dc85694b7b5e5d169662f4936bcd03233 sh -c "cat /etc/*release | grep ^ID"
/usr/bin/tar xz --warning=no-unknown-keyword --overwrite -C /__w/_temp/c6ddb2b4-ec58-40da-aa08-34a8e6e3927e -f /__w/_temp/70db4385-e9d2-4dc6-b8f7-c03271ff101e
Error: google-github-actions/setup-gcloud failed with: EACCES: permission denied, mkdir '/__t/gcloud'
```


> Just wondering, but who creates the directory __t in this case?

```json
{
  "Type": "bind",
  "Source": "/opt/hostedtoolcache",
  "Destination": "/__t",
  "Mode": "",
  "RW": true,
  "Propagation": "rprivate"
}
```

I think it's a mount setup by github actions.

Some other info:
from the runner
```
runner@<container>:/$ ls -l /opt/                
total 0
drwxrwxr-x. 2 root docker 6 May 11 23:45 hostedtoolcache
```

from job (container)
```
docker exec -it b5cccc6b4bb3 bash
bash-5.1$ ls -l /
total 76
drwxr-xr-x.    6 builder builder   76 May 23 21:36 __e
drwxr-xr-x.    2 root    root       6 May 23 21:40 __t
drwxrwxrwx.    6 builder    1001   81 May 23 21:45 __w
...
```

**Comment by mumoshu** [comment]
@Gentoli Thanks a lot for sharing! Would you mind submitting a dedicated issue so that we can actually work on fixing it? (We don't regularly review closed issues so random issues commented in the existing issues would never be actually addressed, unfortunately...

Re the issue, `__t` does seem to be owned by `root` so it should be inaccessible by the `docker` user. It will never work. But then, the question is why did it work before for the `runner` user? 🤔

**Comment by Gentoli** [comment]
Having a second look on it, `__t` in the job container is binding to `/opt/hostedtoolcache` in the `docker` container in the pod. So this is the actual permission is:
```
/ # id
uid=0(root) gid=0(root) groups=0(root),1(bin),2(daemon),3(sys),4(adm),6(disk),10(wheel),11(floppy),20(dialout),26(tape),27(video)
/ # ls -l /opt/
total 0
drwx--x--x    4 root     root            28 May 23 21:36 containerd
drwxr-xr-x    4 root     root            32 May 23 22:24 hostedtoolcache
```
This is probably why it can be read/bind by docker (and owned by `root:root` in the container).

Let me know if you prefer a separate issue than reopening this.

**Comment by mumoshu** [comment]
@Gentoli Thanks! I'd prefer another issue, as that's different from the one originally reported in this issue.

**Comment by mumoshu** [comment]
@Gentoli Ah, so are you basically saying that reverting #337 entirely is the way to go? (As, perhaps, we now noticed that the correct group for hostedtoolcache is actually `runner`(gid 1000) instead of `docker`?
