### ISSUE TITLE
HorizontalAutosclaerController still saves old cache entries,  accumulating until etcd cannot save it any more

### ISSUE THREAD

**Issue by jonico** [summerwind/actions-runner-controller#356]
I believe https://github.com/summerwind/actions-runner-controller/blob/e9eef049933c6154677f9070786b7ea0bb66f361/controllers/horizontalrunnerautoscaler_controller.go#L155
is the reason why #346 is not solved yet - at least in my system it is still accumulating

@mumoshu: ☝️

**Comment by mumoshu** [comment]
@jonico Thanks for reporting ☺️ This definitely looks like a bug. I'll fix it asap.

**Comment by mumoshu** [comment]
#357 should fix this
