### ISSUE TITLE
ListRepositoryWorkflowRuns doesn't return queued runners

### ISSUE THREAD

**Issue by tbl-harmoney** [summerwind/actions-runner-controller#362]
After investigating why autoscaling is not increasing the amount of runners ("desired": "1") although having a queue of over 20 runs with at least 3 queued jobs inside each run, it seems the request to GitHub is returning `{ "total_count": 0 }` runs.

```go
opts := github.ListWorkflowRunsOptions{
    Status: status,
}

for {
    list, res, err := c.Client.Actions.ListRepositoryWorkflowRuns(ctx, user, repoName, &opts)
}
```
(pagination was removed as a test, without success)

However, when executing the request without `opts`, the runs are returned. Printing them shows runs with field `"status": "queued"`.
```go
runs, res, err := c.Client.Actions.ListRepositoryWorkflowRuns(ctx, user, repoName, nil)
```

Raw output after adding some logs and replacing the controller in our cluster with the custom built one:
![image](https://user-images.githubusercontent.com/65944949/109518203-52f8d400-7aaa-11eb-982a-7e4d3d8ff91f.png)

Side question: why would you execute the request without capturing the response? (disclaimer: no experience with Go)
```go
func (c *Client) listRepositoryWorkflowRuns(ctx context.Context, user string, repoName, status string) ([]*github.WorkflowRun, error) {
    c.Client.Actions.ListRepositoryWorkflowRuns(ctx, user, repoName, nil)
```

**Comment by mumoshu** [comment]
@tbl-harmoney Hey! Thanks for reporting

Seems like the missing workflow runs in the API response is due to today's incident on GitHub: https://github.community/t/list-workflow-runs-api-not-detecting-in-progress-builds/165029

> why would you execute the request without capturing the response?

This one seems to be my mistake! I'll fix it asap.

**Comment by tbl-harmoney** [comment]
> Seems like the missing workflow runs in the API response is due to today's incident on GitHub: https://github.community/t/list-workflow-runs-api-not-detecting-in-progress-builds/165029

🤦🏼‍♂️

Thanks for the quick fix! 🚀
