### ISSUE TITLE
Allow communication over HTTP

### ISSUE THREAD

**Issue by pierreyves-lebrun** [summerwind/actions-runner-controller#366]
My company load balancers terminate TLS before proxying traffic to our clusters, so I am looking for a way to bypass cert-manager and expose `actions-runner-controller` service over HTTP.

Is there a straight forward way to achieve that?

**Comment by mumoshu** [comment]
@pierreyves-lebrun Hey! Sorry but I don'get it. Which part of the actions-runner-controller which is being exposed to your LB requires TLS? Validating/mutating webhooks requires TLS but hey won't be exposed to the LB. Are you talking about the runner autoscaler webhook server? But it doesn't require TLS.

**Comment by pierreyves-lebrun** [comment]
Thanks for your prompt answer!

Basically I exposed `actions-runner-actions-runner-controller-webhook` service with type `NodePort` and put a load balancer in front of it as my setup is an on-prems cluster.

The thing is when I try to communicate with the controller, the `manager` container throws the following error:
`http: TLS handshake error from 10.233.90.26:33366: remote error: tls: bad certificate`

I am assuming that is because my load balancer uses a different certificate to handle incoming connections, terminates TLS and then forwards traffic over HTTP to the controller service.

I could be missing something but I was under the impression this chart does't support such a setup.

**Comment by mumoshu** [comment]
@pierreyves-lebrun I'm not yet sure if this might be a bug in our helm chart or anything else. But anyway-

If you're trying to expose the autoscaler webookh server via your LB, you will need to expose [`github-webhook-server` service](https://github.com/summerwind/actions-runner-controller/blob/master/charts/actions-runner-controller/templates/githubwebhook.service.yaml) via NodePort. It doesn't speak TLS so it should just work.

And this might be the important thing I had to say first- `github-webhook-server` needs the unreleased version of actions-runner-controller to work. More concretely, you need to set `image.tag` to `canary` to use the unreleased version in your values.yaml https://github.com/summerwind/actions-runner-controller/blob/master/charts/actions-runner-controller/values.yaml#L25

**Comment by pierreyves-lebrun** [comment]
I managed to workaround the problem by changing my infrastructure and can now confirm the error message was caused by my load balancer trying to communicate over HTTP to `actions-runner-actions-runner-controller-webhook` which is actually expecting traffic over HTTPS.

I will definitely look at enabling `github-webhook-server`, thanks a lot for your explanation and for such a quick answer!

**Comment by mumoshu** [comment]
@pierreyves-lebrun Thanks for confirming! To be extra sure, normally you shouldn't expose the mutating/validating webhook server. It is typically used only by the K8s API server that is within your cluster, and there would be no specific reason for you to interact with it directly, which negates the necessity of the LB in front of them.

On the other hand, exposing github-webhook-server is the requisite to make the whole solution work. Hope this helps.
