### ISSUE TITLE
New Auth Token Format

### ISSUE THREAD

**Issue by callum-tait-pbx** [summerwind/actions-runner-controller#369]
Probably not an issue but I noticed in the changelog that they are updating the format of the auth tokens. Just raising an issue to highlight this, feel free to close if this isn't going to be a problem @mumoshu 

https://github.blog/changelog/2021-03-04-authentication-token-format-updates/

**Comment by callum-tait-pbx** [comment]
This has been released and no one reported anything broken 🎉 , wasn't a problem then I guess :D

**Comment by mumoshu** [comment]
@callum-tait-pbx Hope so! Thanks for your help
