### ISSUE TITLE
[Question] Is it possible to register a runner to multiple repositories (without registering to org?)

### ISSUE THREAD

**Issue by Disturbing** [summerwind/actions-runner-controller#389]
Wondering if it's possible to add multiple repositories to a runner versus just one. In some cases we may not want to grant org-wide permissions for security reasons, but being able to register a single runner to multiple repositories, it would be great to know if this is possible or not?

Many thanks in advance!

**Comment by mumoshu** [comment]
@Disturbing Hey! Unfortunately, it's not possible due to how GitHub Actions API works. A runner can only be registered to single repo/org by its definition. All you can do is create two RunnerDeployment for respective repos.

**Comment by jonico** [comment]
@Disturbing: what you can do though is to assign the runner at org scope, has it register to a specific runner group and grant that runner group to only the repositories of your choice: https://docs.github.com/en/actions/hosting-your-own-runners/managing-access-to-self-hosted-runners-using-groups
Doing so, your runners cannot be used by other repos and will also not try to "grab" queued jobs in other repos.

**Comment by Disturbing** [comment]
I see, thanks!

My use case though was to have one runner for multiple repositories without
giving permission to the org scope as I don’t want a runner running for
every single repository all the time.

The solution to have one shared pool of runners via org scope is the
correct way though, I’ll just need to get access to the scope since I’m not
an org admin yet, so getting a PAT for that will take some time.
