### ISSUE TITLE
Stuck runners

### ISSUE THREAD

**Issue by arhue** [summerwind/actions-runner-controller#39]
Hi,

Firstly thank you for the wonderful project. It was much needed. Everything was working well for me before I tried moving my self hosted runners from dev env to production env. Now I have a bunch of runners that I can't seem to delete:

```
arhue@hp-laptop:~/git$ kubectl get runners
NAME                      REPOSITORY            STATUS
ga-unittest-6glhx-74d28   tectonic/awardforce   
ga-unittest-6glhx-crp9v   tectonic/awardforce   
ga-unittest-wzj5j-l6r4t   tectonic/awardforce   
ga-unittest-wzj5j-zmjnd   tectonic/awardforce   
```

```
arhue@hp-laptop:~/git/infrastructure-helm$ kubectl delete runners --force ga-unittest-6glhx-74d28
warning: Immediate deletion does not wait for confirmation that the running resource has been terminated. The resource may continue to run on the cluster indefinitely.
runner.actions.summerwind.dev "ga-unittest-6glhx-74d28" force deleted
^C
```
I waited almost 10 mins but they didn't get deleted. This is what my runner deployment looks like:

```
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: ga-unittest
  namespace: default
spec:
  replicas: 2
  template:
    spec:
      repository: tectonic/awardforce
      ImagePullPolicy: Always
      image: xxx/infra:actions-runner
      resources:
        limits:
          cpu: "4.0"
          memory: "8Gi"
        requests:
          cpu: "2.0"
          memory: "4Gi"
      sidecarContainers:
        - name: mysql
          image: mysql:5.7
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: abcd1234
          securityContext:
            runAsUser: 0
```

No pods come up. There seems to be an error in runners:

```
Events:
  Type     Reason                         Age                 From               Message
  ----     ------                         ----                ----               -------
  Warning  FailedUpdateRegistrationToken  25m (x21 over 64m)  runner-controller  Updating registration token failed
```

I tried adding new tokens and app credentials but that change anything. Would like some help on how I can delete the runners created earlier and how I can spin up new ones. Config is managed with helmfile.

**Comment by arhue** [comment]
I tried adding an another runnerdeployment:

```
Building dependency release=actions-runner, chart=../helm-charts/actions-runner
Decrypting secret /home/arhue/git/infrastructure-helm/prod/values/secrets.github.yaml
Decrypting /home/arhue/git/infrastructure-helm/prod/values/secrets.github.yaml

Comparing release=actions-runner, chart=../helm-charts/actions-runner
********************

	Release was not present in Helm.  Diff will show entire contents as new.

********************
actions-runner-system, controller-manager, Secret (v1) has been added:
+ # Source: actions-runner/templates/secret.yaml
+ apiVersion: v1
+ kind: Secret
+ metadata:
+   name: controller-manager
+   namespace: actions-runner-system
+ data:
+   github_app_id: '++++++++ # (5 bytes)'
+   github_app_installation_id: '++++++++ # (7 bytes)'
+   github_app_private_key: '++++++++ # (1675 bytes)'
+   github_token: '++++++++ # (40 bytes)'
+ type: Opaque
  
default, actions-runner, RunnerDeployment (actions.summerwind.dev) has been added:
- 
+ # Source: actions-runner/templates/ga-unittest.yaml
+ apiVersion: actions.summerwind.dev/v1alpha1
+ kind: RunnerDeployment
+ metadata:
+   name: actions-runner
+   namespace: default
+ spec:
+   replicas: 2
+   template:
+     spec:
+       repository: tectonic/awardforce
+       ImagePullPolicy: Always
+       image: xxx/infra:actions-runner
+       resources:
+         limits:
+           cpu: "4.0"
+           memory: "8Gi"
+         requests:
+           cpu: "2.0"
+           memory: "4Gi"
+       sidecarContainers:
+         - name: mysql
+           image: mysql:5.7
+           env:
+             - name: MYSQL_ROOT_PASSWORD
+               value: abcd1234
+           securityContext:
+             runAsUser: 0

```

But it doesn't seem to work. 

```
arhue@hp-laptop:~/git/infrastructure-helm$ kubectl get runners
NAME                      REPOSITORY            STATUS
ga-unittest-6glhx-74d28   tectonic/awardforce   
ga-unittest-6glhx-crp9v   tectonic/awardforce   
ga-unittest-wzj5j-l6r4t   tectonic/awardforce   
ga-unittest-wzj5j-zmjnd   tectonic/awardforce   
arhue@hp-laptop:~/git/infrastructure-helm$ kubectl get runnerdeployment
NAME             DESIRED   CURRENT   READY
actions-runner   2                   
```

```
arhue@hp-laptop:~/git/infrastructure-helm$ kubectl get pods | grep runner
arhue@hp-laptop:~/git/infrastructure-helm$ 
```


Would appreciate any help.

**Comment by mumoshu** [comment]
> No pods come up. There seems to be an error in runners:

Hey! I'm a bit confused - Are you able to successfully creat any runner pods? Or is it just that it creates successfully but never gets deleted?

**Comment by arhue** [comment]
>Are you able to successfully creat any runner pods? Or is it just that it creates successfully but never gets deleted?

No for both.

Runners got created the first time but now new ones aren't getting created and earlier ones are not getting deleted.

```
arhue@hp-laptop:~/git/infrastructure-helm$ kubectl get runners
NAME                      REPOSITORY            STATUS
ga-unittest-6glhx-74d28   tectonic/awardforce   
ga-unittest-6glhx-crp9v   tectonic/awardforce   
ga-unittest-wzj5j-l6r4t   tectonic/awardforce   
ga-unittest-wzj5j-zmjnd   tectonic/awardforce   
arhue@hp-laptop:~/git/infrastructure-helm$ kubectl get runnerdeployments
NAME             DESIRED   CURRENT   READY
actions-runner   2                   
```

The first output shows earlier runners but I can't seem to remove them and runners for new runnerdeployments aren't getting created.

**Comment by mumoshu** [comment]
@arhue Thanks! Then, does recreating the github token used by the controller help?

I believe the runner controller is really calling a few GItHub API for registering/deleting runners on your behalf (oh API token you provided) here.

It would fail like that if the token is not valid anymore. That's why I'm doubting if the token is still valid.

**Comment by arhue** [comment]
@mumoshu I tried that. However the runners still appear to be stuck. The issue is that they aren't re-trying the keys or anything. The last retry was hours ago when it first failed. They are just stuck!

**Comment by mumoshu** [comment]
@arhue Hey! Thanks for the additional info.

> The issue is that they aren't re-trying the keys or anything

How did you confirm that?

Perhaps it's just that I'm not understanding your issue correctly but the repeated `FailedUpdateRegistrationToken` events you're seeing is due to the controller was really unable to register the runner with your API token.

https://github.com/summerwind/actions-runner-controller/blob/5714459c24e7cad727eeefe2d188aedcadb47c39/controllers/runner_controller.go#L113

And the message in the Age of the event "25m (x21 over 64m)" does mean that it retried 20 times.

**Comment by arhue** [comment]
@mumoshu Oh. That makes sense. However new runners are not getting created for them to re-try. I have recreated all the keys necessary.

**Comment by mumoshu** [comment]
@arhue Then we must be seeing wrong logs/places.

Could you share me the full log of actions-runner-controller pod and all the runner pods, redacting credentials, for debugging purpose?

**Comment by arhue** [comment]
@mumoshu Logs for  actions-runner-controller pod. No runner pods are running.

```
2020-04-21T05:15:03.813Z	ERROR	controllers.Runner	Failed to unregister runner	{"runner": "default/ga-unittest-wzj5j-zmjnd", "error": "failed to remove runner: GET https://api.github.com/repos/tectonic/awardforce/actions/runners?per_page=10: 404 Not Found []"}
github.com/go-logr/zapr.(*zapLogger).Error
	/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
github.com/summerwind/actions-runner-controller/controllers.(*RunnerReconciler).Reconcile
	/workspace/controllers/runner_controller.go:88
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:256
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:232
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:211
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190913080033-27d36303b655/pkg/util/wait/wait.go:152
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190913080033-27d36303b655/pkg/util/wait/wait.go:153
k8s.io/apimachinery/pkg/util/wait.Until
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190913080033-27d36303b655/pkg/util/wait/wait.go:88
2020-04-21T05:15:03.813Z	ERROR	controller-runtime.controller	Reconciler error	{"controller": "runner", "request": "default/ga-unittest-wzj5j-zmjnd", "error": "failed to remove runner: GET https://api.github.com/repos/tectonic/awardforce/actions/runners?per_page=10: 404 Not Found []"}
github.com/go-logr/zapr.(*zapLogger).Error
	/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:258
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:232
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:211
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190913080033-27d36303b655/pkg/util/wait/wait.go:152
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190913080033-27d36303b655/pkg/util/wait/wait.go:153
k8s.io/apimachinery/pkg/util/wait.Until
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190913080033-27d36303b655/pkg/util/wait/wait.go:88
```
Now it makes sense why they aren't getting removed.

**Comment by mumoshu** [comment]
@arhue Thanks! Yeah, AFAIK that happens only when the token is wrong or invalid(you may know but some web services return 404 on authorization failure, not to leak the existence of the resource), or you've specified non-existent repository.

For me with a valid token, HTTP GET requests to an existing repo does respond with 200:

```
$ curl -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/myorg/myrepo/actions/runners?per_page=10
{
  "total_count": 0,
  "runners": [

  ]
}
```

**Comment by arhue** [comment]
@mumoshu With the same token:

```
arhue@hp-laptop:~/git/infrastructure-helm$ curl -H "Authorization: token 1cda279db46fd6a26b210a3a5a849f337eb689a4" https://api.github.com/repos/tectonic/awardforce/actions/runners?per_page=10
{
  "total_count": 2,
  "runners": [
    {
      "id": 37,
      "name": "z1d-test",
      "os": "linux",
      "status": "offline"
    },
    {
      "id": 38,
      "name": "ip-10-100-120-20",
      "os": "linux",
      "status": "online"
    }
  ]
}
```

**Comment by arhue** [comment]
I think the issue is that it is trying to delete those runners but is unable to since they don't actually exist.

**Comment by mumoshu** [comment]
@arhue Interesting! It could be. I thought you've already tried `kubectl delete --force`.

I'd suggest
```
kubectl delete runners --grace-period=0 --force $RUNNER_NAME

**Comment by mumoshu** [comment]
To reduce number of hops until this is resolved, if the above doesn't work, I'd suggest removing everything forcefully.

You'd need to remove resources in this order:

- RunnerDeployment
- RunnerReplicaSet
- Runner
- Pod

It's this order because the upper resource manages the lower, and the forceful deletion of the upper one means K8s doesn't automagically remove the lower one.

**Comment by arhue** [comment]
@mumoshu Thanks for sticking with me for this.

>I'd suggest..

That didn't work. They are still there.

>followed by..

There aren't any pods.

>To reduce number of hops needed until this is resolved - if the above doesn't work, I'd suggest removing everything forcefully.

Tried that. RunnerDeployment got deleted, there weren't any RunnerReplicaSet, Runners didn't get deleted and there aren't any pods.

**Comment by mumoshu** [comment]
@arhue Thanks!

Oh - so are you basically saying that `kubectl delete runners --grace-period=0 --force $RUNNER_NAME` does succeed but after that you still see some runners with `kubectl get runners`, right?

**Comment by arhue** [comment]
@mumoshu Correct. By "succeeds" it gives a deleted message but gets stuck there. I have to Ctrl+C the operation after a while.

```
arhue@hp-laptop:~/git/infrastructure-helm$ kubectl delete runners --grace-period=0 --force ga-unittest-6glhx-74d28
warning: Immediate deletion does not wait for confirmation that the running resource has been terminated. The resource may continue to run on the cluster indefinitely.
runner.actions.summerwind.dev "ga-unittest-6glhx-74d28" force deleted


^C
arhue@hp-laptop:~/git/infrastructure-helm$ kubectl get runners
NAME                      REPOSITORY            STATUS
ga-unittest-6glhx-74d28   tectonic/awardforce   
ga-unittest-6glhx-crp9v   tectonic/awardforce   
ga-unittest-wzj5j-l6r4t   tectonic/awardforce   
ga-unittest-wzj5j-zmjnd   tectonic/awardforce   
```

**Comment by mumoshu** [comment]
@arhue Ahh okay! That makes sense. Sorry, but apparently I had been misunderstanding that how `--force --grace-period=0` works in this case.

Could you please try removing `spec.finalizers` from each runner resource in `kubectl edit runner $RUNNER_NAME`? The `kubectl delete` would work then.

**Comment by arhue** [comment]
@mumoshu That worked! I tried adding it back just to see what happens. I get these in the logs:

```
2020-04-23T03:02:04.730Z	DEBUG	controller-runtime.manager.events	Warning	{"object": {"kind":"Runner","namespace":"default","name":"actions-runner-9kcgt-jks86","uid":"b911b90b-5b8b-442e-82d8-8ab24d1b0e5a","apiVersion":"actions.summerwind.dev/v1alpha1","resourceVersion":"63472352"}, "reason": "FailedUpdateRegistrationToken", "message": "Updating registration token failed"}
2020-04-23T03:02:06.237Z	ERROR	controllers.Runner	Failed to get new registration token	{"runner": "default/actions-runner-9kcgt-k8skd", "error": "failed to create registration token: POST https://api.github.com/repos/tectonic/awardforce/actions/runners/registration-token: 404 Not Found []"}
github.com/go-logr/zapr.(*zapLogger).Error
	/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
github.com/summerwind/actions-runner-controller/controllers.(*RunnerReconciler).Reconcile
	/workspace/controllers/runner_controller.go:114
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:256
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:232
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:211
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190913080033-27d36303b655/pkg/util/wait/wait.go:152
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190913080033-27d36303b655/pkg/util/wait/wait.go:153
k8s.io/apimachinery/pkg/util/wait.Until
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190913080033-27d36303b655/pkg/util/wait/wait.go:88
2020-04-23T03:02:06.238Z	ERROR	controller-runtime.controller	Reconciler error	{"controller": "runner", "request": "default/actions-runner-9kcgt-k8skd", "error": "failed to create registration token: POST https://api.github.com/repos/tectonic/awardforce/actions/runners/registration-token: 404 Not Found []"}
github.com/go-logr/zapr.(*zapLogger).Error
	/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:258
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:232
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:211
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190913080033-27d36303b655/pkg/util/wait/wait.go:152
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190913080033-27d36303b655/pkg/util/wait/wait.go:153
k8s.io/apimachinery/pkg/util/wait.Until
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190913080033-27d36303b655/pkg/util/wait/wait.go:88
2020-04-23T03:02:06.238Z	DEBUG	controller-runtime.manager.events	Warning	{"object": {"kind":"Runner","namespace":"default","name":"actions-runner-9kcgt-k8skd","uid":"b1d99bb3-10a8-464e-b043-436cb05bed8c","apiVersion":"actions.summerwind.dev/v1alpha1","resourceVersion":"63472354"}, "reason": "FailedUpdateRegistrationToken", "message": "Updating registration token failed"}
```

Any idea what could be going wrong?

**Comment by mumoshu** [comment]
@arhue Invalid token, invalid token scope,  invalid request path, or inexistent repo? 🤔 

Could you try grabbing the exact github token used by your runner with

```
kubectl get secret controller-manager \
    -n actions-runner-system \
    -o jsonpath={.data. github_token} | base64 -D
```

And use that to register a runner token yourself:

```
curl -X POST -H "Authorization: token xxx" https://api.github.com/repos/tectonic/awardforce/actions/runners/registration-token
```

**Comment by arhue** [comment]
@mumoshu 

```
curl -X POST -H "Authorization: token 9e...." https://api.github.com/repos/tectonic/awardforce/actions/runners/registration-token
{
  "token": "AB.....",
  "expires_at": "2020-04-23T09:53:10.347+05:30"
}
```

**Comment by mumoshu** [comment]
@arhue Ummm, that seems like impossible.

Are you sure that you've grabbed the token from `kubectl get secret controller-manager`? (Sorry but I'm really really curious. This is really impossible to occur when everything is correct.

**Comment by arhue** [comment]
@mumoshu Correct. I'm totally confused too. Everything with similar configuration worked fine in dev env.

**Comment by mumoshu** [comment]
@arhue May I ask what's the difference between the dev env and the env you're running into this issue?

For example, a kind of corporate forward proxy, it's collocated within the same k8s cluster(but in different namespaces) or not, etc

**Comment by arhue** [comment]
@mumoshu I think I fixed it! Let me give a full synopsis of what happened.

1. I set up dev env with just github_token secret. Everything worked as expected.
2. I saw the new instructions in README.md which asked to add 3 more secrets, which I did.

```
  github_app_id: {{ .Values.github_app_id | replace ":" "" | b64enc }}
  github_app_installation_id: {{ .Values.github_app_installation_id | replace ":" "" | b64enc }}
  github_app_private_key: {{ .Values.github_app_private_key | b64enc }}
```

I forgot to restart the controller manager pod so thought everything went fine.

3. I moved everything over to prod env and started getting this very weird behaviour. 
4. I removed github_app_id, github_app_installation_id and github_app_private_key secrets and everything started working again as expected.

Any idea if these secrets be added or not? The readme is a bit confusing regarding this and there isn't much supporting documentation. Really appreciate the patience you've had with me. I don't mind writing some documentation if it is needed.

**Comment by mumoshu** [comment]
@arhue Glad to hear that you finally made it!

Regarding the GitHub App creds and the token, you only need either of them. If you'd like let the actions-runner-controller to authenticate as a GitHub App, you'd want to give it github_app_{id,installation_id,private_key}.

If you don't care, using the token alone would be easy to go, which means that you only need `github_token` in the secret.

Does this clarify it?

**Comment by summerwind** [comment]
Oh, this is my bad. You can choose whether to use Personal Access Token or GitHub Apps. If you are using Personal Access Token, you do not need to set the following secrets.

- `github_app_id`
- `github_app_installation_id`
- `github_app_private_key`

**Comment by arhue** [comment]
@mumoshu @summerwind Got it! Thank you for your patience and the help. Can I submit a PR to improve the readme docs? I think it is very easy to get confused as things are currently.

**Comment by mumoshu** [comment]
@arhue We'd appreciate it!

**Comment by arhue** [comment]
Thanks. I'll put in a PR in some time. Closing the issue for now. Thank you once again.

**Comment by igorbrigadir** [comment]
> @arhue Ahh okay! That makes sense. Sorry, but apparently I had been misunderstanding that how `--force --grace-period=0` works in this case.
> 
> Could you please try removing `spec.finalizers` from each runner resource in `kubectl edit runner $RUNNER_NAME`? The `kubectl delete` would work then.

This also helped me solve a similar stuck runner issue. For anyone else looking, this command was very helpful for finding any "stuck" resources in the `actions-runner-system` namespace:

```
kubectl api-resources --verbs=list --namespaced -o name | xargs -n 1 kubectl get --show-kind --ignore-not-found -n actions-runner-system
```
