### ISSUE TITLE
Releasing new version

### ISSUE THREAD

**Issue by kimxogus** [summerwind/actions-runner-controller#399]
There's no release since 0.17.0, there are many new features like webhook server, but that's only in helm chart template and canary tag. I can use canary tag, but as it's not stable, I'm afraid to use that. Is there a release plan for a new version?

**Comment by mumoshu** [comment]
@kimxogus It can be tomorrow or next week, depending on good/bad reports from early testers like you!

Personally speaking, I'm pretty confident that it's reliable enough to deserve a new release after the latest patch I just made(#398), though.

(Ideally, this should be more streamlined like "release on green build" but honestly speaking our integration test suite seems too limited that it doesn't catch many bugs reported by you all.

**Comment by callum-tait-pbx** [comment]
@mumoshu I'd certainly appreciate a new release at this point as soon as possible as I am waiting for the next release before I am going to start the process of mass adoption in my org (don't feel pressured to do one though if you don't feel the codebase is ready!)

**Comment by mumoshu** [comment]
The good news is that I've just released v0.18.0 with numerous improvements :tada:

https://github.com/summerwind/actions-runner-controller/releases/tag/v0.18.0
