### ISSUE TITLE
Failed to update runner status for Registration

### ISSUE THREAD

**Issue by int128** [summerwind/actions-runner-controller#400]
After https://github.com/summerwind/actions-runner-controller/pull/398 (commit 2929a739e34ceb72467f45b4ab36286ea0be4728), I got another error:

```console
2021-03-18T02:27:39.251Z	ERROR	controllers.Runner	Failed to update runner status for Registration	{"runner": "NAME", "error": "Runner.actions.summerwind.dev \"NAME\" is invalid: [status.message: Required value, status.phase: Required value, status.reason: Required value]"}
github.com/go-logr/zapr.(*zapLogger).Error
	/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
github.com/summerwind/actions-runner-controller/controllers.(*RunnerReconciler).updateRegistrationToken
	/workspace/controllers/runner_controller.go:467
github.com/summerwind/actions-runner-controller/controllers.(*RunnerReconciler).Reconcile
	/workspace/controllers/runner_controller.go:150
```

It seems this caused the error:
https://github.com/summerwind/actions-runner-controller/blob/3cccca8d097222a1022a16a9cd2e42bcdb1459b8/controllers/runner_controller.go#L466-L467

**Comment by funkypenguin** [comment]
I have the same issue, on the latest `canary` tag pulled about 30 min ago:

```
2021-03-18T03:35:04.123Z	ERROR	controller-runtime.controller	Reconciler error	{"controller": "runner-controller", "request": "sandbox/runner.elpenguino.net", "error": "Runner.actions.summerwind.dev \"runner.elpenguino.net\" is invalid: [status.message: Required value, status.phase: Required value, status.reason: Required value]"}
github.com/go-logr/zapr.(*zapLogger).Error
```

My runner spec is really simple:

```
apiVersion: actions.summerwind.dev/v1alpha1
kind: Runner
metadata:
  name: runner.elpenguino.net
  namespace: sandbox
spec:
  organization: redacted
```

**Comment by mumoshu** [comment]
@int128 @funkypenguin Hey! Thanks- Reports from early testers are super helpful. I think I managed to fix this in #404. Note that you will probably need to recreate Runner CRD in order to make it work.

> AFAICS from my limited testing, you may also need to delete/create the Runner CRD to make it work.

From what I saw, `kubectl apply -f charts/actions-runner-controller/crds/actions.summerwind.dev_runners.yaml` didn't actually update changes under `status` field, which is necessary to fix this validation error.

**Comment by mumoshu** [comment]
Please also check #407

**Comment by jonico** [comment]
@mumoshu: ran into that issue as well. will there be an automated update of existing CRDs when you publish an official release?

**Comment by mumoshu** [comment]
@jonico CRDs in https://github.com/summerwind/actions-runner-controller/tree/master/charts/actions-runner-controller/crds are always up-to-date and should immediately be available via a new chart release. But if you're talking about the controller's ability to automatically upgrade CRDs- no, unfortunately. You have to upgrade it by running `kubectl`, or via your CI(e.g. GitHub Actions)/CD(e.g. ArgoCD) 😢
