### ISSUE TITLE
Can not install on GKE using PAT.

### ISSUE THREAD

**Issue by hsblhsn** [summerwind/actions-runner-controller#401]
Hello there!

I am getting this error while setting up with GitHub PAT on GKE.

```
Error: Client creation failed. authentication failed: could not read private key: open /etc/actions-runner-controller/github_app_private_key: no such file or directory
```

Any solution to fix this?

**Comment by mumoshu** [comment]
@hsblhsn Hey! It can happen when you're missing `github_token` key in your `controller-manager` secret.

**Comment by hsblhsn** [comment]
Yeah! I mistakenly passed an empty $GITHUB_TOKEN to the secret. Fixed it. And it works now. Closing.

**Comment by mumoshu** [comment]
@hsblhsn Thanks for confirming! Glad to hear it worked ☺️
