### ISSUE TITLE
How to persist/cache image-based actions

### ISSUE THREAD

**Issue by funkypenguin** [summerwind/actions-runner-controller#403]
Hey guys! I'm trying to move my VM-hosted runners over to pods using actions-runner-controller. I've noticed the runner pod restarts after every job, and thus it doesn't retain any caching/images. Since many of my jobs use multiple actions in docker containers, this makes the disposable, pod-based runner workflows take significantly longer, since each time the actions run, every image is built from its Dockerfile from scratch. Is there a way to "cache" already built images, or avoid the runner restarting at the end of each job?

Thanks!
D

**Comment by mumoshu** [comment]
@funkypenguin Hey!

I opted to make runners ephemeral to just to keep the clean build environment for reproducible builds.

But if you understand the tradeoff and do like to make it immutable, I can suggest removing the `--once` flag from https://github.com/summerwind/actions-runner-controller/blob/master/runner/entrypoint.sh#L71. You should be able to test it on your environment by building a custom runner image and setting it under `Runner.Spec.Image` or `RunnerDeployment.Spec.Template.Image`.

**Comment by funkypenguin** [comment]
Thanks @mumoshu, I'll consider that if the build delay becomes enough of a PITA ;)
