### ISSUE TITLE
make test fails with permission denied

### ISSUE THREAD

**Issue by ToMe25** [summerwind/actions-runner-controller#415]
I have been trying to run the validation snipped with a fresh clone of this repository as a baseline to compare changes to, should i make any, and couldn't get it to run.
After it didn't work on the system i originally tried it on i tried to run it on a fresh minikube installation.
I tried it both on the host system, and on the master node(using minikube ssh).

Running it on the host makes all tests fail to start the control pane, thus not even really starting the tests.
Running it on the kubernetes master(in this case a docker container) causes it to fail with "Permission Denied" when trying to execute the test files, despite the permissions being most likely correct.
I can't say for sure whether the file permissions are correct, because they are deleted very quickly, but the go-build folders are marked as executable.

This is the log of the permission denied thing in the minikube master: [pastebin](https://pastebin.com/K5HiL8Cc)
And this is the log of only one test failing on the same device outside the minikube cluster: [pastebin](https://pastebin.com/dYDqixRr)

BTW do i have to publish a docker build?
I don't have a dockerhub acc, and am lazy so i just disabled that for my tests.

**Comment by mumoshu** [comment]
@ToMe25 Hey! As you have already written above it should all depend on what the exact logs you got.

But anyway, at least you should have `etcd` and `kube-apiserver` binaries installed onto your system before running `make test`, as it uses controller-runtime's integration test framework which relies on those binaries. I remember that those binaries are also distributed as part of [kubebuilder releases](https://github.com/kubernetes-sigs/kubebuilder/releases).

**Comment by ToMe25** [comment]
Because the minikube installation somehow died i first tried it outside of that again, and after reinstalling some things only one of the tests fails.
This is the full output of running the snipped: [pastebin](https://pastebin.com/dYDqixRr)
I think this is the important part of the log:
```
[Fail] Inside of a new namespace when no existing resources exist [It] should adopt RunnerReplicaSet created before 0.18.0 to have Spec.Selector 
/home/tome25/Documents/actions-runner-controller/controllers/runnerdeployment_controller_test.go:476
```
I will still try it in a minikube installation again to get the log from what went wrong there.

**Comment by ToMe25** [comment]
I just ran this again in a new minikube installation(because as i said the old one died), and it still causes the same log.
However now knowing you are supposed to run it on the compilation device, rather then the cluster master i don't think this matters.
Here it is anyways: [pastebin](https://pastebin.com/K5HiL8Cc)

**Comment by mumoshu** [comment]
> you are supposed to run it on the compilation device

Yes.

> [Fail] Inside of a new namespace when no existing resources exist [It] should adopt RunnerReplicaSet created before 0.18.0 to have Spec.Selector

This one seems to have failed due to a slow run, which can be due to limited cpu resource available to your mininkube VM or your desktop/laptop machine. We explicitly use 1s timeout for the failed step here:

https://github.com/summerwind/actions-runner-controller/blob/07f822bb0886ba63ee09ee7ff72661c0194b5c72/controllers/runnerdeployment_controller_test.go#L476

so my best bet would be you need to increase the timeout to 2s, 3s, or whatever greater that works for you.

**Comment by ToMe25** [comment]
I am sorry for not just trying it again then, i just expected a timeout error to say that its a timeout.
This was run during the setup of some minikube stuff, so chances are it would be way faster if i just tried it again.
Will try that soon :)
If it fails i will increase the timeout.

**Comment by ToMe25** [comment]
Now that nothing else is running it just runs through without failing :)
Thanks for the help

**Comment by mumoshu** [comment]
@ToMe25 Great! Thanks for sharing your experience ☺️

**Comment by ToMe25** [comment]
`make test` actually runs without any changed timeouts, however i tried running `make docker-build acceptance`, and that fails with this error:
```
service/controller-manager-metrics-service created
service/webhook-service created
deployment.apps/controller-manager created
certificate.cert-manager.io/serving-cert created
issuer.cert-manager.io/selfsigned-issuer created
Warning: admissionregistration.k8s.io/v1beta1 MutatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 MutatingWebhookConfiguration
mutatingwebhookconfiguration.admissionregistration.k8s.io/mutating-webhook-configuration created
Warning: admissionregistration.k8s.io/v1beta1 ValidatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 ValidatingWebhookConfiguration
validatingwebhookconfiguration.admissionregistration.k8s.io/validating-webhook-configuration created
error: timed out waiting for the condition on deployments/controller-manager
make[1]: *** [Makefile:152: acceptance/tests] Error 1
make[1]: Leaving directory '/home/theodor/Documents/actions-runner-controller'
make: *** [Makefile:130: acceptance] Error 2
```
I have looked around a bit, but i couldn't find it, where can i change this timeout?
I tried running it a few more times, but it always fails here.

**Comment by ToMe25** [comment]
Actually i seem to have found it initially, i just thought it couldn't be that because increasing it a lot didn't fix the crash.
Its in acceptance/deploy.sh, as i initially expected.
