### ISSUE TITLE
Succeeded status, but the runner cannot be queried 

### ISSUE THREAD

**Issue by chenrui333** [summerwind/actions-runner-controller#43]
Today, I saw a weird `Succeeded` for the first time, but found the pod cannot be queried against:

```
NAME                                       REPOSITORY                     STATUS
github-action-runner-gl5c8-zv7vh    xx/xx                  Succeeded

$ kubectl describe pod github-action-runner-gl5c8-zv7vh
Error from server (NotFound): pods "github-action-runner-gl5c8-zv7vh" not found
```

**Comment by summerwind** [comment]
Can you give me the controller's log and, manifest you use?
It's hard to help you with only the resource status.

**Comment by mumoshu** [comment]
The controller has been improved in terms of reliability a lot. We seem to have never encountered this recently. I'm closing this as resolved!
