### ISSUE TITLE
failed to list runners

### ISSUE THREAD

**Issue by sandeepraj-chandrakant-bhandari-db** [summerwind/actions-runner-controller#440]
Hi ,
I am trying to register the runners at an enterprise level. below is my deployment file :

```apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: runnerdeploy1
spec:
  replicas: 2
  template:
    spec:
      enterprise: deutsche-bank
      labels:
        - dind
      image: summerwind/actions-runner-dind:latest
      dockerdWithinRunnerContainer: true
      resources:
        limits:
          cpu: "4000m"
          memory: "2Gi"
        requests:
          cpu: "200m"
          memory: "200Mi"
      volumeMounts:
      - mountPath: /runner
        name: runner
      volumes:
      - name: runner
        emptyDir: {}
```
I am setting below after deploying controller.

kubectl set env deploy controller-manager -c manager GITHUB_ENTERPRISE_URL=https://github.com/enterprises/deutsche-bank --namespace actions-runner-system

I am getting below error 

2021-03-31T07:09:13.336Z    ERROR    controller-runtime.controller    Reconciler error    {"controller": "runner", "request": "default/runnerdeploy1-l2gj5-h4s │
│ jg", "error": "failed to list runners: GET https://github.com/enterprises/deutsche-bank/api/v3/enterprises/deutsche-bank/actions/runners?per_page=10: 404  []" │
│ }

**Comment by mumoshu** [comment]
@sandeepraj-chandrakant-bhandari-db Hey! You seem to be confusing GitHub Enterprise (ASP version of GitHub hosted by you AFAIK) and GitHub SaaS's enterprise (AFAIK). Are you using SaaS version of GitHub? If so, start by omitting GITHUB_ENTERPRISE_URL.

Then, ensure that your github token passed to the controller is valid by running `curl -H "Authorization: bearer $GITHUB_TOKEN"  https://github.com/enterprises/deutsche-bank/api/v3/enterprises/deutsche-bank/actions/runners?per_page=10`. If your token is valid, it should return 200 OK.

**Comment by sandeepraj-chandrakant-bhandari-db** [comment]
@mumoshu thank you so much. Yes we are using the saas version and it worked after omitting the enterprise url.
