### ISSUE TITLE
Prevent auto-update of runner version

### ISSUE THREAD

**Issue by arhue** [summerwind/actions-runner-controller#46]
Whenever there is an update released from Github, it breaks the runners unless you update the binary with the latest version in Docker. Making this issue to explore if the auto-update can be stopped or if it is possible to update the runner automatically.

I'm currently using a script which rebuilds the runner Docker container with a binary from `curl -sL https://api.github.com/repos/:org/:repo/actions/runners/downloads -H "Authorization: token xxx" | jq -r '.[].download_url' | grep linux-x64` and restarts the pods when they stop working due to an update; which is obviously not very ideal.

**Comment by summerwind** [comment]
Thank you for opening this issue!
This is a duplication of #33 with most of the discussion captured there.

**Comment by arhue** [comment]
@summerwind Oops somehow missed it, sorry.
