### ISSUE TITLE
Unable to use docker buildx inside dind runner

### ISSUE THREAD

**Issue by nandiheath** [summerwind/actions-runner-controller#475]
Hi, I have set up some runners for my repository,
however it fails when trying to run `docker buildx build ...`

This is the output
```shell
docker buildx build -f Dockerfile .
unknown shorthand flag: 'f' in -f
See 'docker --help'.

Usage:	docker [OPTIONS] COMMAND
```

and I execute a shell into the runner and seems it has no buildx enabled for the docker. 
is it possible to have the buildx installed for the docker on `summerwind/actions-runner-dind` ?

**Comment by mumoshu** [comment]
@nandiheath Hey!

Our default runner image contains only a subset of packages available in hosted version of the runner. See https://github.com/summerwind/actions-runner-controller#software-installed-in-the-runner-image. So you are very likely to need to install docker buildx extension on your own in your workflow. I thought there was a github action that does it for you.

**Comment by callum-tait-pbx** [comment]
https://github.com/summerwind/actions-runner-controller/blob/master/.github/workflows/build-and-release-runners.yml we actually use the setup action within the runner build and release workflow

```yaml
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
```

**Comment by nandiheath** [comment]
cool! Really thank you for the quick response!
I will try with the buildx-action. Much appreciated!
