### ISSUE TITLE
Few README issues

### ISSUE THREAD

**Issue by jgournet** [summerwind/actions-runner-controller#483]
Hi !
Thanks for providing all this.
While following the README instructions for installation, I saw a few minor issues, so listing them here:
1) using helm install, we need to create the namespace before:
```
kubectl create namespace actions-runner-system
```
Then, the right command is:
```
helm upgrade --install -n actions-runner-system actions-runner-controller actions-runner-controller/actions-runner-controller
```
(the current one was missing the "helm release name")
2) lastly, after installing, the secret already exists - had to update it with:
```
kubectl create secret generic controller-manager     -n actions-runner-system     --from-literal=github_token=${GITHUB_TOKEN} --save-config --dry-run=client -o yaml | kubectl apply -f -
```

Minor issues, but that might help other people

**Comment by krisztiankoszegi** [comment]
With helm you can create the namespace also: 

`helm upgrade --install --namespace actions-runner-system --create-namespace --wait actions-runner-controller actions-runner-controller/actions-runner-controller`
