### ISSUE TITLE
Helm chart contribution

### ISSUE THREAD

**Issue by kuuji** [summerwind/actions-runner-controller#61]
Hey there!

I wrote a helm 3 chart that I'm currently using to deploy this. I'm willing to contribute it to this repo if you're interested. I just wanted to gauge your interest before working on a PR.

**Comment by summerwind** [comment]
Thank you for considering the contribution.
It sounds great! You are always welcome to create a PR 😄

**Comment by pedrofracassi** [comment]
I'm looking forward to this one!

**Comment by boredland** [comment]
would like that very much!

**Comment by mabushey** [comment]
Please look at Kustomize. It runs circles around Helm.

**Comment by mumoshu** [comment]
Implemented in #187 and seem to be working great. Closing as resolved
