### ISSUE TITLE
Effect by depreciation of "installation" and "installation_repositories" events

### ISSUE THREAD

**Issue by maratdr** [summerwind/actions-runner-controller#70]
Thank a lots for starting and maintaining this project.

It's been used in my organization widely and making github action runner deployment very easy.

I just received a notification from Github regarding the replacement of "installation" and "installation_repositories" events
https://developer.github.com/changes/2020-04-15-replacing-the-installation-and-installation-repositories-events/

Just wonder whether this change will break the controller?

**Comment by mumoshu** [comment]
Hey. It doesn't break anything for the controller, as it doesn't rely on github webhook in the first place.
I'm closing this as answered but please feel free to reopen if necessary.
