### ISSUE TITLE
Make controller also look at queued jobs.

### ISSUE THREAD

**Issue by helder-moreira** [summerwind/actions-runner-controller#89]
A running workflow may have multiple queued jobs. The controller could add more runners based on this.

As an example: I have a `RunnerDeployment` with autoscaling enabled between 3 and 20 instances. One of the workflows I run, has 6 parallel jobs, of which 3 will be always queued.

I can try to make a PR with this over the next few days if you are open to it.

**Comment by dlobue** [comment]
@helder-moreira FYI I have a PR up that adds this functionality.

**Comment by helder-moreira** [comment]
@dlobue perfect! Thank you 🙏
